// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdJYQrqc1SIK9KyMtbLbDs_onzlP0nHjI',
    appId: '1:357124304692:web:aa921987173716f815ff61',
    messagingSenderId: '357124304692',
    projectId: 'coy-house-calender',
    authDomain: 'coy-house-calender.firebaseapp.com',
    storageBucket: 'coy-house-calender.firebasestorage.app',
    measurementId: 'G-MFTDYXXHLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_mzFx2ZodRKcjQjuKWEGfP4LvHCpOk88',
    appId: '1:357124304692:android:729f90202a5edb4515ff61',
    messagingSenderId: '357124304692',
    projectId: 'coy-house-calender',
    storageBucket: 'coy-house-calender.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv4vjK0TMiM1M1qpOpLMZS9GoR8mZdv24',
    appId: '1:357124304692:ios:3f6c4909d6142af615ff61',
    messagingSenderId: '357124304692',
    projectId: 'coy-house-calender',
    storageBucket: 'coy-house-calender.firebasestorage.app',
    iosBundleId: 'com.example.testCalender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv4vjK0TMiM1M1qpOpLMZS9GoR8mZdv24',
    appId: '1:357124304692:ios:3f6c4909d6142af615ff61',
    messagingSenderId: '357124304692',
    projectId: 'coy-house-calender',
    storageBucket: 'coy-house-calender.firebasestorage.app',
    iosBundleId: 'com.example.testCalender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdJYQrqc1SIK9KyMtbLbDs_onzlP0nHjI',
    appId: '1:357124304692:web:6b86ea676025035415ff61',
    messagingSenderId: '357124304692',
    projectId: 'coy-house-calender',
    authDomain: 'coy-house-calender.firebaseapp.com',
    storageBucket: 'coy-house-calender.firebasestorage.app',
    measurementId: 'G-QV1ZM31JNW',
  );
}
